name: flutter_subscreen_plugin
description: The plug-in supports double screen Android device, and uses flutter to draw the main and secondary screens to realize communication and interaction between the two screens
version: 1.0.7
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/flutter_subscreen_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rex.flutter_subscreen_plugin
        pluginClass: FlutterSubscreenPlugin
